Vagrant.configure("2") do |config|

config.ssh.insert_key = false
config.vm.provider :virtualbox do |vb|
  vb.memory = 4096
  vb.cpus = 2
end

#Disabling the default /vagrant share
config.vm.synced_folder ".", "/vagrant", disabled: true
MACHINE = ["arango1","arango2","arango3"]
N = 2

(0..N).each do |i|
config.vm.define "server#{i}" do |node|
  node.vm.hostname = MACHINE[i]
  node.vm.box = "generic/ubuntu2004"
  node.vm.network :private_network, ip: "192.168.56.#{100+i}"
end
end
end