---
# tasks file for arangodb download and install

- name: Create the arangodb Group
  group:
    name: arangodb
    state: present 
  become: true

- name: Add arangodb User
  user:
    name: arangodb 
    create_home: no
    groups: arangodb
  become: true

- name: Download and Install ArangoDB
  ansible.builtin.unarchive: 
    src: https://download.arangodb.com/9c169fe900ff79790395784287bfa82f0dc0059375a34a2881b9b745c8efd42e/arangodb38/Enterprise/Linux/arangodb3e-linux-3.8.1.tar.gz
    dest: /usr/local
    remote_src: yes
  become: true

- name: Create required folders for Arangodb 
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
    owner: arangodb
    group: arangodb
  loop:
    - { path: "/var/tmp/arangodb3" }
    - { path: "/var/run/arangodb3" }
    - { path: "/var/log/arangodb3" }
    - { path: "/var/lib/arangodb3" }
    - { path: "/var/lib/arangodb3-apps" }
    - { path: "/etc/arangodb3" }
  become: true

- name: Copy configuration files to the /etc/arangodb/config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '644'
  loop:
    - { src: "/vagrant/config/cluster/agent.conf", dest: "/etc/arangodb3/agent.conf"}
    - { src: "/vagrant/config/cluster/coordinator.conf", dest: "/etc/arangodb3/coordinator.conf"}
    - { src: "/vagrant/config/cluster/dbserver.conf", dest: "/etc/arangodb3/dbserver.conf"}
    - { src: "/vagrant/config/systemdunits/agent.service", dest: "/etc/systemd/system/agent.service"}
    - { src: "/vagrant/config/systemdunits/coordinator.service", dest: "/etc/systemd/system/coordinator.service"}
    - { src: "/vagrant/config/systemdunits/dbserver.service", dest: "/etc/systemd/system/dbserver.service"}
  become: true
  vars:
    starter_join_ips: "192.168.0.20:8528,192.168.0.21:8528,192.168.0.22:8528"
