---
# tasks file for arangodb download and install
- name: Download and Install ArangoDB
  ansible.builtin.unarchive: 
    src: https://download.arangodb.com/9c169fe900ff79790395784287bfa82f0dc0059375a34a2881b9b745c8efd42e/arangodb38/Enterprise/Linux/arangodb3e-linux-3.8.1.tar.gz
    dest: /usr/local
    remote_src: yes
  become: true

